In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3.5,"hello"] #list m multiple data type ho skte h
a

[1, 2, 3.5, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Array generation function
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [21]:
#Linear Spacing
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [22]:
#Random generation Function
np.random.rand(10)
#normalize form 0 to 1

array([0.68775455, 0.44376024, 0.67533843, 0.07288772, 0.50864038,
       0.6169093 , 0.52265794, 0.26275314, 0.25369029, 0.1042963 ])

In [24]:
np.random.randn(10)
# standardize form -3 to 3

array([ 0.72259271, -0.09947327, -1.37931121,  0.30333701, -1.23590796,
        0.43879421,  0.34121927,  0.4659572 ,  0.70419444,  0.12280295])

In [25]:
# random integer generate krna 
np.random.randint(10,20,5)

array([10, 19, 18, 19, 11], dtype=int32)

In [26]:
# Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int64')

In [32]:
# Array Method
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.min()

np.int64(1)

In [34]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [36]:
np.sum(arr,axis=0)
# ye column wise sum krta h

array([12, 15, 18])

In [37]:
np.sum(arr,axis=1)
# ye row wise sum krta h

array([ 6, 15, 24])

In [38]:
arr.mean()

np.float64(5.0)

In [39]:
arr.std()

np.float64(2.581988897471611)

In [40]:
arr.argmax()
# maximum element h uska index btata h

np.int64(8)

In [41]:
arr.argmin()
# minimum element h uska index btata h

np.int64(0)

In [42]:
# Reshaping and Resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr = arr.reshape(6,5)  # usko arr m store krke resize kr diya
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])