In [1]:
import numpy as np

In [2]:
# Arithmetic operationab
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
a1//a2

array([0, 0, 0, 0, 0])

In [7]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [8]:
# Broadcasting
l = [10,20,30,40]
arr = np.array(l)


In [9]:
arr + 10

array([20, 30, 40, 50])

In [30]:
# Deep and Shallow  copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a[4:6] *10


array([50, 60])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a
b = a

In [36]:
b[0] = 99

In [37]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
a
b = a.copy()
b[0] =99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
# Matrix Operation
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [40]:
A

array([[1, 2],
       [3, 4]])

In [41]:
B

array([[5, 6],
       [7, 8]])

In [42]:
A*B

array([[ 5, 12],
       [21, 32]])

In [43]:
# matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [45]:
# Transpose
A.T

array([[1, 3],
       [2, 4]])

In [47]:
# Stacking of Array
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])

In [48]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
# Splitting Array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]