In [1]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [6]:
#Slicing
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arrSlice = arr[3::2]
arrSlice

array([14, 16, 18, 20])

In [10]:
# Numpy Indexing and slicing of matrix
arr  = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[0][1]

np.int64(2)

In [17]:
#slicing matrix
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [19]:
arr[3:6,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
# ek particular cloumn print krvane k liye
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [21]:
#Boolean Indexing
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
bool_index = arr %2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])