In [1]:
#Valid Sudoku
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])



In [2]:
s.sum()

np.int64(405)

In [3]:
b= np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("Suduko is no valid")
        break
else:
    print("valid")

valid


In [4]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("Suduko is no valid")
        break
else:
    print("valid")

valid


In [5]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [6]:
# Get the shape of matrix
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data.shape

(5, 3)

In [7]:
np.mean(data[:,0]) # mean of age

np.float64(18.4)

In [8]:
data[:,1]  #c math marks for all student

array([85, 92, 76, 65, 90])

In [9]:
np.max(data[:,2])  # max marks for science student

np.int64(95)

In [10]:
# get details of student who scored more than 90 marks
data [data[:,1]>90]


array([[19, 92, 88]])

In [11]:
# increase maths marks of all students by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [12]:
# find how many student are younger than 19

data[data[:,0]<19]


array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [13]:
#Claculatre the average marks in each subject
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [14]:
# get data of students who scored at least 80 nin both subject
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [15]:
# Replace all Science marks< 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])